import { Platform } from "react-native";

export const KinovaColors = {
  rubyRed: "#E53935",
  sunsetOrange: "#FF9800",
  limeGreen: "#8BC34A",
  tealCyan: "#00BCD4",
  royalBlue: "#2196F3",
  violetPurple: "#9C27B0",
};

export const CategoryColors = {
  calendar: KinovaColors.royalBlue,
  lists: KinovaColors.sunsetOrange,
  notes: KinovaColors.violetPurple,
  budget: KinovaColors.limeGreen,
  assistant: KinovaColors.tealCyan,
  profile: KinovaColors.royalBlue,
  home: KinovaColors.rubyRed,
};

export const CategoryBackgrounds = {
  light: {
    calendar: "#E3F2FD",
    lists: "#FFF3E0",
    notes: "#F3E5F5",
    budget: "#F1F8E9",
    assistant: "#E0F7FA",
    profile: "#E3F2FD",
    home: "#FFEBEE",
  },
  dark: {
    calendar: "#0D1F2D",
    lists: "#1A1408",
    notes: "#1A0D1F",
    budget: "#0D1A0D",
    assistant: "#0D1A1F",
    profile: "#0D1F2D",
    home: "#1F0D0D",
  },
};

export const RainbowButtonColors = {
  red: KinovaColors.rubyRed,
  orange: KinovaColors.sunsetOrange,
  green: KinovaColors.limeGreen,
  cyan: KinovaColors.tealCyan,
  blue: KinovaColors.royalBlue,
  purple: KinovaColors.violetPurple,
};

export const Gradients = {
  rainbow: [KinovaColors.rubyRed, KinovaColors.sunsetOrange, KinovaColors.limeGreen, KinovaColors.tealCyan, KinovaColors.royalBlue, KinovaColors.violetPurple],
  primary: [KinovaColors.royalBlue, "#42A5F5"],
  coral: [KinovaColors.sunsetOrange, "#FFB74D"],
  green: [KinovaColors.limeGreen, "#AED581"],
  purple: [KinovaColors.violetPurple, "#BA68C8"],
  teal: [KinovaColors.tealCyan, "#4DD0E1"],
  red: [KinovaColors.rubyRed, "#EF5350"],
  oceanBlue: [KinovaColors.royalBlue, "#42A5F5"],
  sunriseCoral: [KinovaColors.sunsetOrange, "#FFB74D"],
  meadowGreen: [KinovaColors.limeGreen, "#AED581"],
  lavenderBloom: [KinovaColors.violetPurple, "#BA68C8"],
  sunshineYellow: ["#FFC107", "#FFD54F"],
};

export const Colors = {
  light: {
    primary: KinovaColors.royalBlue,
    secondary: KinovaColors.sunsetOrange,
    accent: KinovaColors.violetPurple,
    accentYellow: "#FFC107",
    accentGreen: KinovaColors.limeGreen,
    accentTeal: KinovaColors.tealCyan,
    accentRed: KinovaColors.rubyRed,
    text: "#212121",
    textSecondary: "#616161",
    textLight: "#9E9E9E",
    buttonText: "#FFFFFF",
    tabIconDefault: "#757575",
    tabIconSelected: KinovaColors.royalBlue,
    link: KinovaColors.royalBlue,
    backgroundRoot: "#FFFFFF",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#FAFAFA",
    backgroundTertiary: "#F5F5F5",
    surface: "#FFFFFF",
    border: "#E0E0E0",
    borderLight: "#EEEEEE",
    success: KinovaColors.limeGreen,
    warning: "#FFC107",
    error: KinovaColors.rubyRed,
    info: KinovaColors.tealCyan,
    tabBar: "#FFFFFF",
    inputBackground: "#FFFFFF",
    inputBorder: "#E0E0E0",
    inputBorderFocus: KinovaColors.royalBlue,
    cardBackground: "#FFFFFF",
    rubyRed: KinovaColors.rubyRed,
    sunsetOrange: KinovaColors.sunsetOrange,
    limeGreen: KinovaColors.limeGreen,
    tealCyan: KinovaColors.tealCyan,
    royalBlue: KinovaColors.royalBlue,
    violetPurple: KinovaColors.violetPurple,
    oceanBlue: KinovaColors.royalBlue,
    sunriseCoral: KinovaColors.sunsetOrange,
    meadowGreen: KinovaColors.limeGreen,
    lavenderBloom: KinovaColors.violetPurple,
    sunshineYellow: "#FFC107",
  },
  dark: {
    primary: "#42A5F5",
    secondary: "#FFB74D",
    accent: "#BA68C8",
    accentYellow: "#FFD54F",
    accentGreen: "#AED581",
    accentTeal: "#4DD0E1",
    accentRed: "#EF5350",
    text: "#FAFAFA",
    textSecondary: "#B0BEC5",
    textLight: "#78909C",
    buttonText: "#FFFFFF",
    tabIconDefault: "#78909C",
    tabIconSelected: "#42A5F5",
    link: "#42A5F5",
    backgroundRoot: "#121212",
    backgroundDefault: "#121212",
    backgroundSecondary: "#1E1E1E",
    backgroundTertiary: "#2C2C2C",
    surface: "#1E1E1E",
    border: "#424242",
    borderLight: "#373737",
    success: "#AED581",
    warning: "#FFD54F",
    error: "#EF5350",
    info: "#4DD0E1",
    tabBar: "#121212",
    inputBackground: "#1E1E1E",
    inputBorder: "#424242",
    inputBorderFocus: "#42A5F5",
    cardBackground: "#1E1E1E",
    rubyRed: "#EF5350",
    sunsetOrange: "#FFB74D",
    limeGreen: "#AED581",
    tealCyan: "#4DD0E1",
    royalBlue: "#42A5F5",
    violetPurple: "#BA68C8",
    oceanBlue: "#42A5F5",
    sunriseCoral: "#FFB74D",
    meadowGreen: "#AED581",
    lavenderBloom: "#BA68C8",
    sunshineYellow: "#FFD54F",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  screenPadding: 20,
  cardPadding: 16,
  componentGap: 12,
  inputHeight: 52,
  buttonHeight: 52,
};

export const BorderRadius = {
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 26,
  full: 9999,
  button: 26,
  input: 12,
  card: 16,
  badge: 20,
};

export const Typography = {
  largeTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700" as const,
    letterSpacing: -0.5,
  },
  title: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "600" as const,
    letterSpacing: -0.2,
  },
  body: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  label: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
    letterSpacing: 0,
  },
  caption: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  small: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  button: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
  },
};

export const IconSize = {
  sm: 18,
  md: 20,
  lg: 24,
  xl: 32,
  navigation: 24,
  inline: 20,
  decorative: 32,
};

export const Shadows = {
  sm: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  md: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  lg: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  button: {
    shadowColor: KinovaColors.royalBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "Inter",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "Inter",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "Inter, 'SF Pro Rounded', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const Animation = {
  spring: {
    damping: 15,
    stiffness: 200,
  },
  duration: {
    fast: 150,
    normal: 250,
    slow: 400,
  },
  pressScale: 0.97,
};
