import { Platform } from "react-native";

export const Colors = {
  light: {
    primary: "#8F867D",
    secondary: "#D4C5B0",
    accent: "#F0A8A8",
    accentYellow: "#F4D89A",
    accentGreen: "#C3E4C8",
    text: "#4A4A4A",
    textSecondary: "#7A7A7A",
    textLight: "#9A9A9A",
    buttonText: "#FFFFFF",
    tabIconDefault: "#D4C5B0",
    tabIconSelected: "#FFFFFF",
    link: "#8F867D",
    backgroundRoot: "#FDFBF9",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#F5F0EB",
    backgroundTertiary: "#EDE8E1",
    surface: "#FFFFFF",
    border: "#E5DED4",
    borderLight: "#EDE8E1",
    success: "#C3E4C8",
    warning: "#F4D89A",
    error: "#E57373",
    info: "#8F867D",
    tabBar: "#8F867D",
    inputBackground: "#FDFBF9",
    inputBorder: "#E5DED4",
    inputBorderFocus: "#8F867D",
    cardBackground: "#FFFFFF",
  },
  dark: {
    primary: "#A69D94",
    secondary: "#D4C5B0",
    accent: "#F0A8A8",
    accentYellow: "#F4D89A",
    accentGreen: "#C3E4C8",
    text: "#F5F0EB",
    textSecondary: "#B8B0A8",
    textLight: "#8A827A",
    buttonText: "#FFFFFF",
    tabIconDefault: "#8A827A",
    tabIconSelected: "#D4C5B0",
    link: "#A69D94",
    backgroundRoot: "#1E1D1C",
    backgroundDefault: "#2A2826",
    backgroundSecondary: "#363432",
    backgroundTertiary: "#424038",
    surface: "#2A2826",
    border: "#4A4744",
    borderLight: "#3A3836",
    success: "#C3E4C8",
    warning: "#F4D89A",
    error: "#E57373",
    info: "#A69D94",
    tabBar: "#2A2826",
    inputBackground: "#2A2826",
    inputBorder: "#4A4744",
    inputBorderFocus: "#A69D94",
    cardBackground: "#2A2826",
  },
};

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  "2xl": 24,
  "3xl": 32,
  "4xl": 40,
  "5xl": 48,
  screenPadding: 20,
  cardPadding: 20,
  inputHeight: 52,
  buttonHeight: 52,
};

export const BorderRadius = {
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  "2xl": 28,
  full: 9999,
  button: 20,
  input: 16,
  card: 20,
};

export const Typography = {
  largeTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "700" as const,
    letterSpacing: -0.5,
  },
  title: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "700" as const,
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "600" as const,
    letterSpacing: -0.2,
  },
  body: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  label: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  caption: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  small: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "400" as const,
    letterSpacing: 0,
  },
  button: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
  },
};

export const IconSize = {
  sm: 18,
  md: 22,
  lg: 24,
  xl: 28,
  navigation: 24,
};

export const Fonts = Platform.select({
  ios: {
    sans: "Inter",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "Inter",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "Inter, 'SF Pro Rounded', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
